import { ArrowUpRight, ArrowRight, LockKeyhole, Globe, Check, GitPullRequest, BriefcaseBusiness, Users, Code2 } from 'lucide-react';
import Submission from './submission';
import '../v2/v2.css';
import './developers.css';
export const metadata={title:'Build and distribute Wrapps — Switchboard',description:'Build lightweight software that connects to the user’s AI, tools and context. Explore private deployment and our proposed public developer programme.'};
const repo='https://github.com/sameeeeeeep/switchboard';
export default function Developers(){return <div className="v2 developer-page">
<header className="v2-header"><a className="v2-logo" href="/v2">SWITCHBOARD</a><nav><a href="#distribution">Distribution</a><a href="#earn">Earn</a><a href={repo+'/blob/main/docs/BUILDING-A-WRAPP.md'} className="v2-nav-download">Read the docs <ArrowUpRight size={14}/></a></nav></header>
<main>
<section className="dev-hero"><span className="v2-kicker">FOR DEVELOPERS</span><h1>Build something<br/><em>people can use.</em></h1><p>A focused app shouldn’t need another AI setup. Build its interface and agent behaviour. Switchboard connects it to the user’s AI, configured tools and permitted local context.</p><div className="dev-actions"><a className="v2-primary" href="#start">Start building <ArrowRight size={16}/></a><a href="#distribution">Choose how to distribute it <ArrowDownIcon/></a></div><div className="dev-contract"><Code2/><span>Your app</span><ArrowRight/><span>Switchboard</span><ArrowRight/><span>Their AI + tools + context</span></div></section>
<section id="distribution" className="dev-section"><span className="v2-kicker">TWO WAYS TO DISTRIBUTE</span><h2>For your people.<br/><em>Or for everyone.</em></h2><div className="dev-options">
<article><div className="dev-option-top"><LockKeyhole size={25}/><span>PRIVATE</span></div><h3>Your app. Your audience.</h3><p>Build for yourself, a client or a team. Host the interface where you choose and share it privately. Each user connects their own Switchboard.</p><ul><li><Check/>Keep your repository private.</li><li><Check/>Control hosting and access.</li><li><Check/>Use the user’s approved AI and resources.</li></ul><a href={repo+'/blob/main/docs/BUILDING-A-WRAPP.md'}>Read the integration guide <ArrowUpRight size={15}/></a></article>
<article><div className="dev-option-top"><Globe size={25}/><span>PUBLIC · PROPOSED PROGRAMME</span></div><h3>Open source. Open to users.</h3><p>Submit your GitHub repository for review. We’re building a route for accepted Wrapps to be hosted by Switchboard and discovered in the public directory.</p><ul><li><Check/>Your repository remains the source.</li><li><Check/>Push updates for review before release.</li><li><Check/>A hosted app with a developer credit.</li></ul><a href="#submit">Prepare a repository submission <ArrowRight size={15}/></a></article>
</div><p className="dev-note">Public hosting and update verification are the proposed publishing programme. A submission is a review request, not an automatic deployment.</p></section>
<section className="dev-review dev-section"><span className="v2-kicker">THE PUBLIC PUBLISHING FLOW</span><div className="dev-review-steps">{[['01','Submit','Share the repository, licence, setup instructions and requested capabilities.'],['02','Review','The app and its requested access are reviewed before publication.'],['03','Distribute','Accepted Wrapps get a hosted listing that users can connect to their setup.'],['04','Update','Push to your repository. Changes go through review before reaching users.']].map(([n,title,body])=><div key={n}><span>{n}</span><h3>{title}</h3><p>{body}</p></div>)}</div></section>
<section id="earn" className="dev-earn"><div><span className="v2-kicker">GOOD OPEN SOURCE CAN OPEN DOORS</span><h2>Let your work<br/><em>bring you work.</em></h2><p>A useful public Wrapp is something people can try. It can also show an enterprise exactly what you could build for them.</p></div><div className="dev-earning-paths"><article><BriefcaseBusiness size={23}/><h3>Custom work for enterprises</h3><p>Our proposed developer programme connects public Wrapp creators with businesses that want adaptations, integrations or private versions of their work.</p></article><article><Users size={23}/><h3>Revenue sharing for selected developers</h3><p>We’re exploring a shared-revenue programme around Pro early access to features and updates. Selected developers would participate under agreed terms.</p></article><small>Programme details, selection and commercial terms are still being developed. Publishing open source does not guarantee paid work or revenue.</small></div></section>
<section id="start" className="dev-section dev-start"><div><span className="v2-kicker">MAKE YOUR FIRST CONNECTION</span><h2>Bring the app.<br/><em>Connect the rest.</em></h2><p>Switchboard is free for individual users. Their AI provider’s usage and pricing still apply.</p><a className="v2-primary" href={repo+'/blob/main/docs/BUILDING-A-WRAPP.md'}>Open the full quickstart <ArrowUpRight size={16}/></a></div><ol><li><span>01</span><div><h3>Add the SDK</h3><code>npm install @relay/sdk</code></div></li><li><span>02</span><div><h3>Ask for the access your app needs</h3><p>Use the standard connect control. Declare supported models and tools; let the user approve the scope.</p></div></li><li><span>03</span><div><h3>Use the connected resources</h3><p>Call the SDK for AI and supported context operations. Handle denied access and unavailable capabilities clearly.</p></div></li><li><span>04</span><div><h3>Test with a fresh user</h3><p>Check installation, permissions, model availability and results. Then share privately or request public review.</p></div></li></ol></section>
<section id="submit" className="dev-section dev-submit"><div><img src="/connectors/github.svg" width="28" height="28" alt="GitHub"/><h2>Bring your<br/><em>repository.</em></h2><p>Prepare a public review request on GitHub. Include your licence, how to run the app, its capabilities and a working demo if available.</p></div><Submission/></section>
<footer className="v2-footer"><a className="v2-logo" href="/v2">SWITCHBOARD</a><a href={repo}>Source & documentation <ArrowUpRight size={14}/></a></footer>
</main></div>}
function ArrowDownIcon(){return <ArrowRight size={15} style={{transform:'rotate(90deg)'}}/>}
