'use client';
import {useEffect, useState} from 'react';
import {ArrowUp, Check, FileText, Sparkles, ArrowRight, Laptop, ShieldCheck, Code2, KeyRound, Play, RotateCcw} from 'lucide-react';
export function AppleIcon(){return <svg viewBox="0 0 24 24" width="18" height="18" fill="currentColor" aria-hidden="true"><path d="M17.05 12.54c.03 3.11 2.73 4.15 2.76 4.16-.02.07-.43 1.48-1.43 2.94-.87 1.26-1.77 2.52-3.19 2.55-1.39.03-1.84-.83-3.43-.83-1.59 0-2.09.8-3.41.86-1.37.05-2.42-1.37-3.29-2.63-1.79-2.58-3.15-7.3-1.31-10.48.91-1.58 2.55-2.58 4.33-2.6 1.35-.03 2.63.91 3.46.91.83 0 2.39-1.13 4.03-.97.68.03 2.58.27 3.8 2.05-.1.06-2.27 1.32-2.25 4.04ZM14.43 4.72c.73-.88 1.22-2.1 1.09-3.32-1.05.04-2.32.7-3.07 1.58-.67.77-1.25 2-1.09 3.18 1.17.09 2.35-.59 3.07-1.44Z"/></svg>}
export function ProductScene({id}:{id:string}){const [selected,setSelected]=useState(0);const [phase,setPhase]=useState(3);const [running,setRunning]=useState(false);
useEffect(()=>{if(!running)return;const timers=[window.setTimeout(()=>setPhase(1),800),window.setTimeout(()=>setPhase(2),1900),window.setTimeout(()=>{setPhase(3);setRunning(false)},3300)];return()=>timers.forEach(window.clearTimeout)},[running]);
const prompt=id==='brandbrain'?'Build Verra, a skincare brand for a simpler daily routine. Use my product notes.':id==='adforge'?'Make three ads for Verra. Keep our positioning and brand voice.':'Explore a logo for Verra. Use the brand direction we already developed.';
return <div className={'product-scene product-'+id}>
<div className="demo-request"><span className="demo-request-label">YOUR BRIEF</span><p>{prompt}</p><button disabled={running} onClick={()=>{setPhase(0);setRunning(true)}}>{running?<span className="demo-running-dot"/>:<Play size={12}/>} {running?'Playing example':'Play example'}</button></div><div className="demo-runline" aria-live="polite"><span data-done={phase>=1}><FileText size={12}/>Verra context</span><i/><span data-done={phase>=2}><Sparkles size={12}/>Your AI</span><i/><span data-done={phase>=3}><Check size={12}/>In your app</span></div><div className="demo-result" data-visible={phase===3}><div className="product-project"><span className="verra-word">verra</span><span><FileText size={12}/> Brand context attached</span></div>
{id==='brandbrain'?<><div className="product-section-label">FOUNDATION / MARKET</div><h3>A simpler daily ritual.</h3><p className="product-lead">A skincare brand for people who want fewer steps, and more clarity.</p><div className="brand-directions"><div><small>AUDIENCE</small><strong>Routine minimalists</strong><p>Everyday essentials. A routine they can keep.</p></div><div><small>POSITIONING</small><strong>Less, but considered.</strong><p>Clear ingredients. One uncomplicated ritual.</p></div></div><div className="product-status"><Check size={13}/>Market brief saved to Verra</div></>:id==='adforge'?<><div className="product-section-label">CAMPAIGN / CREATIVE DIRECTIONS</div><h3>One brand. Three angles.</h3><div className="ad-concepts">{['Less to think about.','Your daily essential.','Made for real mornings.'].map((line,i)=><button onClick={()=>setSelected(i)} aria-pressed={selected===i} key={line} className={'ad-concept concept-'+i}><span className="ad-brand">verra</span><span className="serum-bottle"><i/><b>v.</b></span><strong>{line}</strong><small>{['ROUTINE','PRODUCT','LIFESTYLE'][i]}</small></button>)}</div><div className="product-status"><Sparkles size={13}/>{['Routine-led concept selected','Product-led concept selected','Lifestyle concept selected'][selected]}</div></>:<><div className="product-section-label">IDENTITY / EXPLORE DIRECTIONS</div><h3>A mark that feels like Verra.</h3><div className="logo-options">{['verra','v.','VERRA'].map((word,i)=><button aria-pressed={selected===i} onClick={()=>setSelected(i)} className={'logo-direction logo-'+i} key={word}><strong>{word}</strong><span>{['Everyday warmth','The essential mark','Quiet confidence'][i]}</span></button>)}</div><div className="product-status"><Check size={13}/>Same audience. Same palette. A new expression.</div></>}
</div></div>}
export function SharedBrand(){const [asset,setAsset]=useState('all');const palette=['#d3d1ae','#637752','#eee6d4'];return <div className="asset-transfer" data-highlight={asset}>
<div className="asset-origin"><header><img src="/wrapps/brandbrain.png" alt=""/><span>Brandbrain <small>VERRA BRAND KIT</small></span><Check size={14}/></header><div className="asset-source-items">
<button className="asset-source asset-colours" aria-pressed={asset==='colours'} onClick={()=>setAsset(asset==='colours'?'all':'colours')}><span className="asset-swatches">{palette.map(c=><i key={c} style={{background:c}}/>)}</span><strong>Brand colours</strong></button>
<button className="asset-source asset-logo" aria-pressed={asset==='logo'} onClick={()=>setAsset(asset==='logo'?'all':'logo')}><span className="asset-wordmark">verra</span><strong>Logo</strong></button>
<button className="asset-source asset-photo" aria-pressed={asset==='photo'} onClick={()=>setAsset(asset==='photo'?'all':'photo')}><span className="asset-product"><i/><b>v.</b></span><strong>Product image</strong></button>
</div></div>
<div className="asset-routing" aria-hidden="true"><svg viewBox="0 0 600 70" preserveAspectRatio="none"><path d="M100 0V16H300M500 0V16H300M300 0V43M300 43H145V70M300 43H455V70"/><path className="asset-flow-signal" d="M100 0V16H300V43H145V70M500 0V16H300V43H455V70"/></svg><span>THROUGH SWITCHBOARD</span></div>
<div className="asset-destinations"><article><header><img src="/wrapps/adforge.png" alt=""/><span>AdForge</span><small>YOUR NEXT AD</small></header><div className="asset-ad asset-colours"><span className="asset-wordmark asset-logo">verra</span><span className="asset-product asset-photo"><i/><b>v.</b></span><strong>Less to think about.<br/>More to feel good about.</strong><span className="asset-ad-cta">Find your daily ritual ↗</span></div><footer><Check size={11}/>Your colours, logo and product image</footer></article>
<article><header><img src="/wrapps/redline.png" alt=""/><span>Website</span><small>YOUR STOREFRONT</small></header><div className="asset-store asset-colours"><nav><span className="asset-wordmark asset-logo">verra</span><span>Shop · About</span></nav><div className="asset-store-hero"><strong>Skincare.<br/>Simplified.</strong><span className="asset-product asset-photo"><i/><b>v.</b></span></div><span className="asset-store-button">Meet your daily essential</span><div className="asset-store-detail">ONE SIMPLE RITUAL. EVERY DAY.</div></div><footer><Check size={11}/>The same assets, used in your website</footer></article></div>
<small className="scene-disclosure">Illustrated asset handoff · select an asset to trace it</small></div>}
export function SetupReuse(){const [provider,setProvider]=useState('claude');return <div className="setup-reuse"><div className="reuse-provider-tabs" aria-label="Illustrated AI connection">{['claude','codex'].map(id=><button key={id} onClick={()=>setProvider(id)} aria-pressed={provider===id}><img src={'/brands/'+(id==='claude'?'claude-code':'codex')+'.png'} alt=""/>{id==='claude'?'Claude Code':'Codex'}</button>)}</div><div className="reuse-account"><span className="connected-dot"/><strong>Your existing account</strong><span>CONNECTED ONCE</span></div><div className="reuse-connection"><span/><span className="reuse-matrix">{Array.from({length:21},(_,i)=><i key={i}/>)}</span><span/></div><div className="reuse-apps">{[['brandbrain','Brandbrain'],['adforge','AdForge'],['crest','Crest']].map(([id,name])=><span key={id}><img src={'/wrapps/'+id+'.png'} alt=""/>{name}</span>)}</div><p>Different apps. The same AI connection.</p></div>}
export function MacSetup(){return <div className="mac-ready"><div className="mac-ready-screen"><div className="mac-menu"><AppleIcon/><span>Switchboard</span><span className="mac-ready-status">CONNECTED</span></div><div className="mac-ready-main"><span className="mac-dotmark">{Array.from({length:35},(_,i)=><i key={i}/>)}</span><strong>Your setup is ready.</strong><div className="mac-provider-row"><img src="/brands/claude-code.png" alt="Claude Code"/><img src="/brands/codex.png" alt="Codex"/><span>YOUR AI</span></div><div className="mac-wrapp-dock">{['brandbrain','adforge','flow','crest'].map(id=><img src={'/wrapps/'+id+'.png'} alt={id} key={id}/>)}</div></div></div><div className="mac-ready-base"/><p><Laptop size={15}/>Your everyday Mac. Your existing AI. Ready for Wrapps.</p></div>}
export function TrustMarks(){return <section className="v2-trust-marks" aria-label="Trust and ownership"><a href="https://github.com/sameeeeeeep/switchboard"><Code2/>OPEN SOURCE<ArrowRight size={13}/></a><span><AppleIcon/>RUNS ON YOUR MAC</span><span><ShieldCheck/>PERMISSIONED ACCESS</span><span><KeyRound/>YOUR AI ACCOUNT</span></section>}
