/* oxlint-disable next/no-html-link-for-pages -- Static Vite export uses document navigation between published routes. */
/* oxlint-disable next/no-img-element -- Static Vite export serves local image assets directly. */
import type {ReactNode} from 'react';
import {ArrowUpRight, Plus, Code2, BookOpen, GitPullRequest, Bug} from 'lucide-react';
const repo='https://github.com/sameeeeeeep/switchboard';
const questions:[string,ReactNode][]=[
 ['What is a harness?',<>The structure around an AI that helps it do a particular job: instructions, tools, context, an interface and the points where you decide. Switchboard supplies the connection to supported AI and capabilities; the harness shapes how they work together.</>],
 ['What is a Wrapp?',<>A focused app you open to do a job, such as developing a brand or exploring ad concepts. A Wrapp can provide the interface for a harness, using Switchboard to connect to your AI, tools and project context.</>],
 ['Do I have to build anything?',<>No. Start with an existing Wrapp or use capabilities such as dictation and guided steps at the notch. If you want to build your own, the <a href="/developers">SDK and integration guide</a> are the starting point.</>],
 ['What do I need to get started?',<>An Apple Silicon Mac running macOS 13 or later, Switchboard, and a supported AI setup. Connect Claude Code or Codex, or use local models for supported tasks. Web Wrapps also need the <a href="https://chromewebstore.google.com/detail/injmjolmnekmahlnackakiamjepegagb">browser extension</a>.</>],
 ['Is Switchboard free?',<>Yes. Switchboard is free for individual users. You use your existing AI account; its pricing and usage limits still apply. Any paid tools you connect retain their own charges.</>],
 ['Do I need another AI subscription for every app?',<>No. Compatible Wrapps can use the AI you have connected to Switchboard. You choose which apps can access it. Switchboard doesn’t add model capacity or bypass your provider’s limits.</>],
 ['Which AI can I use?',<>Claude Code and Codex are supported. Local models such as Ollama and Whisper handle supported text and voice tasks. Each Wrapp determines which capabilities it needs.</>],
 ['Can websites use files on my Mac?',<>Compatible web Wrapps can request access through Switchboard. You choose the projects and resources they may use. A website doesn’t get unrestricted access to your Mac.</>],
 ['Does everything stay on my device?',<>Switchboard runs on your Mac. When a task uses a cloud model or external connector, the information needed for that request goes to that service. Supported local-model tasks can run on-device.</>],
 ['Does it work with web and native apps?',<>Yes. Web Wrapps connect through the browser extension; native Wrapps use the local Switchboard connection. Apps need a Switchboard integration—it doesn’t automatically connect every installed app.</>],
 ['Will my existing connectors work?',<>Wrapps can use supported tools configured in the connected AI runtime, within the access you allow. Availability differs between Claude Code and Codex; connectors from a chat account don’t automatically carry over.</>],
 ['What carries across when I switch apps?',<>The project context you permit: a brand brief, voice, product notes or other supported files. Compatible Wrapps can read that shared context, and save supported outputs back to the project.</>],
 ['Can I build or distribute my own Wrapp?',<>Yes. Start with one job, build its interface and behaviour, and connect supported capabilities through the SDK. You can distribute your Wrapp privately. See the <a href="/developers">developer page</a> for the quickstart and the status of public publishing programmes.</>],
];
export function Questions(){return <section id="v2-faq" className="v2-questions" aria-labelledby="v2-faq-title"><div className="questions-heading"><span className="v2-kicker">A FEW THINGS TO KNOW</span><h2 id="v2-faq-title">Before you<br/><em>connect.</em></h2><p>Setup, privacy, and what runs where.</p><a href={repo+'/blob/main/docs/BUILDING-A-WRAPP.md'}>Read the docs <ArrowUpRight size={14}/></a></div><div className="questions-list">{questions.map(([question,answer])=><details key={String(question)}><summary>{question}<Plus size={16}/></summary><div className="question-answer">{answer}</div></details>)}</div></section>}
export function OpenSource(){return <section className="v2-open-source" aria-labelledby="source-title"><div><span className="v2-kicker">BUILT IN THE OPEN</span><h2 id="source-title">See how<br/><em>it works.</em></h2><p>Read the code. Build a Wrapp. Help shape Switchboard.</p><a className="v2-primary" href={repo}><img src="/connectors/github.svg" width="19" height="19" alt=""/>View on GitHub <ArrowUpRight size={16}/></a></div><div className="source-links">{[[Code2,'Explore the source','The code behind Switchboard.',repo],[BookOpen,'Build your first Wrapp','The SDK and integration guide.',repo+'/blob/main/docs/BUILDING-A-WRAPP.md'],[GitPullRequest,'Contribute','See what’s being worked on.',repo+'/pulls'],[Bug,'Report an issue','Help us make it better.',repo+'/issues']].map(([Icon,title,description,href])=>{const Symbol=Icon as typeof Code2;return <a key={String(title)} href={String(href)}><Symbol size={20}/><span><strong>{String(title)}</strong><small>{String(description)}</small></span><ArrowUpRight size={15}/></a>})}</div></section>}
