// One illustrated launch, carried through six interfaces. These are not live runs.
export const journeyOrder = [0, 3, 4, 1, 2, 5];
export const journey = {
  brand: { label: 'Research', output: 'market-brief.md', tools: ['files', 'web'], steps: ['Read brief', 'Research market', 'Map competition'], captions: ['“Help me create Verra, a simpler skincare brand.”', 'Your request starts Brandbrain’s research harness.', 'Your voice becomes a prompt, locally.', 'Switchboard connects the Verra project you allow.', 'Your AI reads the notes and researches the market.', 'Brandbrain displays the market summary.', 'The harness compares competitors and their positioning.', 'Brandbrain suggests a market gap to explore.', 'The market brief joins your Verra project.', 'Hear the findings through local speech.', 'Next: use the same brief to build the product listing.'] },
  listing: { label: 'Product', output: 'product-listing.md', tools: ['files', 'web'], steps: ['Read product', 'Use brand brief', 'Build listing'], captions: ['“Turn that brand into a product listing.”', 'A-Plus starts its listing harness.', '', 'A-Plus reads the same Verra brief.', 'Your AI reads the product page through its tools.', 'A-Plus drafts the product description.', 'Product benefits use the positioning in your brief.', 'A complete listing appears in A-Plus.', 'The listing joins the same Verra project.', '', 'Next: bring the product and brand story to the website.'] },
  website: { label: 'Website', output: 'website-review.md', tools: ['files', 'github'], steps: ['Read website', 'Compare voice', 'Suggest edits'], captions: ['“Make our website sound like Verra.”', 'Redline starts the website review harness.', '', 'Redline reads Verra’s brief and product details.', 'Your AI reads the connected website project.', 'The review compares your copy with the brand.', 'Clearer product language appears in the page.', 'You see the suggested edits in context.', 'The website review stays with Verra.', '', 'Next: use this same brand direction for campaign concepts.'] },
  ads: { label: 'Creative', output: 'ad-concepts.md', tools: ['files', 'image'], steps: ['Read brand', 'Draft concepts', 'Create visuals'], captions: ['“Now make three ads for this brand.”', 'AdForge starts the creative harness.', '', 'AdForge reads the positioning saved in Verra’s brief.', 'Your AI calls the configured image tool.', 'AdForge displays the first ad concept.', 'The next concept focuses on the product.', 'Three concepts, grounded in the same brand.', 'The creative directions join the Verra project.', '', 'Later: open the campaign results in AdPulse.'] },
  performance: { label: 'Review', output: 'campaign-review.md', tools: ['meta'], steps: ['Read Meta Ads', 'Diagnose spend', 'Order actions'], captions: ['“What should I scale, fix and stop?”', 'AdPulse starts its campaign diagnosis harness.', '', 'AdPulse gets the Verra brand and campaign context.', 'Your AI reads results through the Meta connector.', 'AdPulse identifies the strongest campaigns.', 'The diagnosis identifies wasted spend.', 'AdPulse lists what to change first.', 'The campaign review joins the same project.', '', 'Next: dictate a launch update without leaving your setup.'] },
  voice: { label: 'Dictate', output: 'launch-note.txt', tools: [], steps: ['Transcribe', 'Clean up', 'Return text'], captions: ['“The Verra launch moves to Friday…”', 'Flow starts a local dictation workflow.', 'Whisper transcribes your voice on this device.', 'Only your allowed personal dictionary is used.', '', 'Ollama cleans up the words locally.', 'Your names and vocabulary stay intact.', 'The note is ready to paste into your next app.', 'Text returns through Switchboard.', 'Hear the note read back locally.', 'Replay this example with your other connected AI.'] },
} as const;
export type JourneyId = keyof typeof journey;
