export const scenarios = [
  {
    id: 'brand', app: 'Brandbrain', mark: 'b.', format: 'a harness for', purpose: 'launching a brand', input: 'text', voice: true, local: false, surface: 'WEB APP',
    appIcon: 'brandbrain', panels: ['Overview', 'Identity', 'Brand voice'], activePanel: 1,
    href: 'https://brandbrain.thelastprompt.ai/build', job: 'Research your brand’s market.',
    prompt: 'Build Verra, a skincare brand for a simpler daily routine. Use my product notes.',
    context: 'Brand brief · audience', connector: 'Project files', resource: 'product-notes.md', icon: 'files',
    action: 'Reading product notes', result: 'Brand direction ready', empty: 'Describe the brand you want to build.',
  },
  {
    id: 'ads', app: 'AdForge', mark: 'af', format: 'an app for', purpose: 'making your next ad', input: 'text', voice: false, local: false, surface: 'WEB APP',
    appIcon: 'adforge', panels: ['Campaign', 'Concepts', 'Brand kit'], activePanel: 1,
    href: 'https://adforge.thelastprompt.ai', job: 'Create ad concepts.',
    prompt: 'Make three ad concepts for Verra. Use our brand voice and create a visual direction.',
    context: 'Brand voice · palette', connector: 'Higgsfield', resource: 'Image generation', icon: 'image',
    action: 'Creating visual directions', result: 'Three concepts ready', empty: 'Describe the ads you want to create.',
  },
  {
    id: 'performance', app: 'AdPulse', mark: 'ap', format: 'an interface for', purpose: 'finding wasted ad spend', input: 'text', voice: false, local: false, surface: 'WEB APP',
    appIcon: 'adpulse', panels: ['Overview', 'Campaigns', 'Insights'], activePanel: 1,
    href: 'https://adpulse.thelastprompt.ai', job: 'Find wasted ad spend.',
    prompt: 'Review Verra’s ad performance. Show me what to scale, fix, and stop.',
    context: 'Brand · product context', connector: 'Meta Ads / CSV', resource: 'Campaign performance', icon: 'chart',
    action: 'Reading campaign data', result: 'Campaign review ready', empty: 'Choose what to investigate in your ad results.',
  },
  {
    id: 'listing', app: 'A-Plus', mark: 'a+', format: 'a harness for', purpose: 'building product listings', input: 'text', voice: false, local: false, surface: 'WEB APP',
    appIcon: 'aplus', panels: ['Product', 'A+ content', 'Preview'], activePanel: 1,
    href: 'https://aplus.thelastprompt.ai', job: 'Build an Amazon A+ listing.',
    prompt: 'Build an Amazon A+ listing for Verra’s Vitamin C serum using our product page.',
    context: 'Brand voice · audience', connector: 'Website reader', resource: 'Product page', icon: 'web',
    action: 'Reading product details', result: 'Product listing ready', empty: 'Add a product to build its listing.',
  },
  {
    id: 'website', app: 'Redline', mark: 'r.', format: 'an interface for', purpose: 'improving your website', input: 'text', voice: false, local: false, surface: 'WEB APP',
    appIcon: 'redline', panels: ['Website', 'Review', 'Changes'], activePanel: 1,
    href: 'https://redline.thelastprompt.ai', job: 'Review your website copy.',
    prompt: 'Review our website. Make the copy clearer and bring it closer to Verra’s brand.',
    context: 'Positioning · brand voice', connector: 'Project files', resource: 'Website project', icon: 'files',
    action: 'Reading your website', result: 'Website review ready', empty: 'Choose a website to review.',
  },
  {
    id: 'voice', app: 'Flow', mark: 'f.', format: 'a native app for', purpose: 'turning voice into words', input: 'voice', voice: true, local: true, surface: 'NATIVE APP',
    appIcon: 'flow', panels: ['Dictation', 'Dictionary', 'History'], activePanel: 0,
    href: 'https://github.com/sameeeeeeep/switchboard/releases/latest', job: 'Dictate text into any app.',
    prompt: 'Write a short note: the Verra launch moves to Friday. The product photos are ready.',
    context: 'Your names · vocabulary', connector: '', resource: '', icon: 'files',
    action: 'Cleaning up your dictation', result: 'Ready to paste', empty: 'Say it in your own words.',
  },
] as const;
